apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-chart
          image: "nginxinc/nginx-unprivileged"

          volumeMounts:
            - name: nginx-index-file
              mountPath: /usr/share/nginx/html/
              
      volumes:
        - name: nginx-index-file
          configMap:
            name: index-html-configmap
