replicaCount: 2

image:
  repository: nginxinc/nginx-unprivileged
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  name: nginx-service
  type: ClusterIP
  port: 80
  targetPort: 80

env:
  name: stage
